version: '2.1'

parameters:
  gio_action:
    type: enum
    enum: [release, blank]
    default: blank
  dry_run:
    type: boolean
    default: false
    description: "Run in dry run mode?"
  maven_profile_id:
    type: string
    default: "gio-release"
    description: "Maven ID of the Maven profile to use for a dry run ?"
  secrethub_org:
    type: string
    default: "gravitee-lab"
    description: "SecretHub Org to use to fetch secrets ?"
  secrethub_repo:
    type: string
    default: "cicd"
    description: "SecretHub Repo to use to fetch secrets ?"

orbs:
  docker: circleci/docker@1.5
  # gravitee: 'gravitee-io/gravitee@dev:1.0.2'
  gravitee: 'gravitee-io/gravitee@1.0.2'
  secrethub: secrethub/cli@1.0.0
jobs:
  empty_job:
    docker:
     - image: alpine
    resource_class: small
    working_directory: /mnt/ramdisk
    steps:
      - run:
          name: "This is a dummy empty job (isn't it ?)"
          command: echo "No task is executed."
  redefine_gravitee_parent:
    machine:
      image: 'ubuntu-1604:201903-01'
      resource_class: medium
    steps:
      # - run:
          # command: |
            # git clone https://github.com/gravitee-lab/gravitee-parent-redefinition ./
            # # git checkout 17.x
            # git checkout 17
            # git checkout -b 17.99.x
          # name: Prepare a new release of the Gravitee Parent POM in reference private maven repository
      - run:
          command: echo "test"
          name: Test
      - checkout
      - secrethub/install
      - docker/install-docker-compose
      - gravitee/mvn_prepare_release:
          dry_run: << pipeline.parameters.dry_run >>
          maven_container_image_tag: stable-latest
          maven_profile_id: << pipeline.parameters.maven_profile_id>>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
      - gravitee/mvn_test_release:
          dry_run: << pipeline.parameters.dry_run >>
          maven_container_image_tag: stable-latest
          maven_profile_id: << pipeline.parameters.maven_profile_id>>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
      - gravitee/mvn_release:
          dry_run: << pipeline.parameters.dry_run >>
          maven_container_image_tag: stable-latest
          maven_profile_id: << pipeline.parameters.maven_profile_id>>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
      # - gravitee/git_release:
          # dry_run: << parameters.dry_run >>
          # maven_container_image_tag: << pipeline.parameters.maven_container_image_tag >>
          # maven_profile_id: << pipeline.parameters.maven_profile_id>>
          # secrethub_org: << pipeline.parameters.secrethub_org >>
          # secrethub_repo: << pipeline.parameters.secrethub_repo >>
workflows:
  # Blank process invoked when ...
  # blank:
    # when:
      # equal: [ blank, << pipeline.parameters.gio_action >> ]
    # jobs:
      # - empty_job:
          # context: cicd-orchestrator
  maven_deploy:
    # when:
      # equal: [ release, << pipeline.parameters.gio_action >> ]
    jobs:
      - redefine_gravitee_parent:
          context: cicd-orchestrator
          filters:
            branches:
              only:
                - 17.99.x
                - 18.99.x
                - 19.99.x
      # - mvn_deploy_gravitee_component:
          # context: cicd-orchestrator
          # requires:
            # - redefine_gravitee_parent
  version: 2.1
